# Programming exercise: PageRank

First, we need to import numpy to get access to all the functions we need:

In [1]:
import numpy as np

If you haven't done so already, read section 10.1 and 10.2 in *Linear Algebra and Its Application* (available on Canvas).
	
**Note**: In this note, indices start at 0. If you are using Matlab, vectors and matrices there are 1-indexed, and you have to adjust accordingly.
	

	
## Directed graphs 
A directed graph is a set of vertices with directed edges between the vertices.

![Adjacency graph](Adjacency_graph.png)

In the PageRank algorithm, each vertex represents a web page, and each edge a link between webpages.

A directed graph can be represented on a computer in several ways. For our purposes, we will focus on the *adjacency matrix*. To form the adjacency matrix of a graph, we first label the ertices of the directed graph with indices  $\{0,1,\dotsc, n-1\}$, where $n$ is the number of vertices.

The adjacency matrix is an $n\times n$-matrix ${A}$, with entries
$$a_{ij}= \begin{cases} 1 & \text{if there is an edge $i\to j$,}\\
						0 & \text{if not.}
							\end{cases}
$$

To set up the adjacency matrix, we put a 1 at position $(i,j)$ if there is an edge $i\to j$, otherwise we put zero.
$$
{A} =
\begin{bmatrix}
	  0 & 1 & 1 & 1 & 0\\
	  0 & 0 & 0 & 0 & 1\\
	  0 & 1 & 0 & 0 & 0\\
	  0 & 0 & 1 & 0 & 0\\
	  1 & 0 & 0 & 1 & 0
	\end{bmatrix}.
$$


This adjacency graph is stored in `adjacency_example.txt`.

We can load it into Python using `np.loadtxt`. If you are using Matlab, you can use `readmatrix`.

In [2]:
A= np.loadtxt('adjacency_example.txt', dtype=int)
print(A)

[[0 1 1 1 0]
 [0 0 0 0 1]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [1 0 0 1 0]]


## The transition matrix
The PageRank Algorithm uses a transition matrix ${P}$ for the random walk across the graph. (See Chapter 10.2 i Lay). This matrix is a stochastic matrix where $p_{ij}$ is the probability of going from state $j$ to state $i$.  


$$
p_{ij}=\begin{cases} \frac{1}{m_j} & \text{if there is an edge $j\to i$}\\
		              0 & \text{otherwise}
	    \end{cases},
$$
where $m_j$ is the number of edges pointing out of node $j$.

**Note:** The adjacency matrix has $a_{ij}\neq 0$ if there is an edge $i\to j$, while the transition matrix has $p_{ij}\neq 0$ if there is an edge $j\to i$.

To compute ${P}$ from ${A}$ we need to do three things:

1. Compute the number of edges going out from each node.
	$$m_i=\sum_{j=0}^{n-1}a_{ij}$$
2. Divide each row of ${A}$ by the corresponding number of edges, resulting in a matrix ${C}$.
	$$c_{ij}=\frac{a_{ij}}{m_i}$$
3. Transpose the resulting matrix.
 	$${P}={C}^\top$$


For our example graph, there are three edges pointiong out of node 0, two edges pointing out of node 3, and one edge pointing out of the other nodes therefore:
$$
\mathbf{m}= \begin{bmatrix}
	3 & 1 & 1 & 1 & 2
\end{bmatrix}^T
$$

After dividing each row of ${A}$ and transposing, we end up with the transition matrix ${P}$.

$$
{P}=\begin{bmatrix}
	0           & 0 & 0 & 0 & \frac{1}{2}\\
	\frac{1}{3}	& 0 & 1 & 0 & 0 \\
    \frac{1}{3}	& 0 & 0 & 1 & 0 \\
	\frac{1}{3} & 0 & 0 & 0 & \frac{1}{2}\\
	0			 & 1 & 0 & 0 & 0
\end{bmatrix}.
$$



### Task 1: Compute the transition matrix
Write a function that takes an adjacency matrix $A$ as input, and returns the corresponding transition matrix $P$.

In [ ]:
def transition_matrix(A):
    '''
    transition_matrix(A):
        Input: 
            A: Adjacency matrix 
        Output:
            P: Transition matrix
    '''
    # Write your implementation here
    return P

For a sanity check, we see if the transition_matrix function returns a stochastic matrix:

In [ ]:
P=transition_matrix(A)
np.allclose(np.sum(P, axis=0), 1) # Will return True if P is a stochastic matrix

## The Power Method:
The PageRank of each node is calculated from the steady-state vector $\mathbf{q}$, defined by
$$P\mathbf{q} =\mathbf{q}, \quad\text{and}\quad \sum_{i=0}^{n-1} q_i=1.
$$
As shown in the lectures, 
$$\mathbf{q}=\lim_{k\to \infty} \mathbf{x}_k,$$
where $\mathbf{x}_k$ is a sequence of probability vectors defined by
$$
\mathbf{x}_{k+1}=P\mathbf{x}_k.
$$



The idea of the power method is to compute the sequence 
$$\mathbf{x}_0,\quad  \mathbf{x}_1=P\mathbf{x}_0,\quad  \mathbf{x}_2 =P\mathbf{x}_1,\quad  \dotsc$$
and use the approximation
$$\mathbf{q}\approx \mathbf{x}_N,
$$
for some large $N$.

**Note:** Here we have assumed that the initial vector $\mathbf{x}_0$ is a probability vector. If it is not, the sequence will converge to some scalar multiple of $\mathbf{q}$ instead. 





### Task 2: The power method
Implement the power method. Your function should take as input the transition matrix, an initial vector of probabilities and the number of iterations of the power method should be used.

In [ ]:
def pow_method(P, v0, N):
    '''
    pow_method(P, v0, N):
        Input: 
            P:   transition matrix
            v0:  initial vector of probabilities
            N:   number of iterations
        Output:
            v:   final vector of probabilities v=P^n * v0
    '''
    # Write your implementation here
    return v

#### Testing the method
For our example graph, $\mathbf{q}$ can be found by solving the homogenous linear equation $\left(P-I\right)\mathbf{q}=0$ and choosing the free parameter such that $\sum_{i=0}^{n-1}q_i=1$.

$$ \begin{aligned}
\mathbf{q}_{\text{exact}}=&\left[\frac{1}{8}, \frac{1}{4}, \frac{5}{24}, \frac{1}{6}, \frac{1}{4}\right]^T\\
\approx&[0.125, 0.25, 0.20833333, 0.16666667, 0.25 ]^T.
\end{aligned}$$
You can use this to test your method. If everything works correctly, your code should return an approcimation of the exact vector.


Increasing `N` should get you even closer to the exact vector.

In [ ]:
n = P.shape[0]    # The number of nodes
x0 = np.ones(n)/n # initial probabilities: 1/n for every node
N=100             # number of iterations

q=pow_method(P,x0,N)
print(q)

### Task 3: NMBU Realtek
In this task, you are going to test your implementation on a set of webpages and links. This set consists of webpages with an url starting with www.nmbu.no/fakultet/realtek and internal links between them (In January 2022). Dangling nodes have been removed.

The adjacency matrix is stored in `adjacency_realtek.txt`, and the urls represented by each index in `keyvals.txt`.

What are the top 5 webpages by PageRank on the RealTek webpages?

Hint: `np.argsort` can be useful for answering this question.

In [ ]:
# Write your code here.

### Task 4: Additional challenges for the interested.

a) In the power method implemented above, we specify the number of iterations. It would be better to iterate until 
$$\|\mathbf{x}_{k}-\mathbf{x}_{k-1}\|\le Tol$$
for some specified tolerance $Tol$. Implement a new function that does this.

*Hint*: `np.linalg.norm` will be useful.
For more efficient code, you should not compute the matrix-vector product $P\mathbf{x}_{k-1}$ more than once per iteration.
It is good practice to implement a maximum number of iterations, so your code doesn't get stuck in an infinite loop.

b) The actual PageRank algorithm is more robust than what we have done here. By making some adjustments, it can handle dangling nodes (webpages without links) and other complications that may arise. Implement Adjustment 1 and 2 described in *Lay* Chapter 10.2.

## Some additional remarks
Our implementation only works for graphs with less than a few thousand nodes. For larger graphs, better implementations are needed. 
Adjacency matrices are usually sparse, that is, most of the entries are zero. Efficient matrix algorithms take advantage of this. In Python, the most used implementation of sparse matrices is scipy.sparse. See https://docs.scipy.org/doc/scipy/reference/sparse.html.

Really efficient implementations of the PageRank algorithm never explicitly store the adjacency matrix or the transition matrix. It is possible to compute a matrix-vector product $P\mathbf{x}$ using only the adjacency list (https://en.wikipedia.org/wiki/Adjacency_list) of the graph.