In [7]:
import numpy as np
import matplotlib.pyplot as plt

In [8]:
# nondiagonalizable matrix:
A = np.array([[1, 1], [0, 1]])
l,v=np.linalg.eig(A)
print('Matrix:\n',A)
print('Eigenvalues:\n',l)
print('Eigenvectors:\n',v.round(5))

Matrix:
 [[1 1]
 [0 1]]
Eigenvalues:
 [1. 1.]
Eigenvectors:
 [[ 1. -1.]
 [ 0.  0.]]


In [9]:
# matrix diagonalizable over C:
A = np.array([[1, 1], [-1, 1]])
l,v=np.linalg.eig(A)
print('Matrix:\n',A)
print('Eigenvalues:\n',l)
print('Eigenvectors:\n',v.round(5))

Matrix:
 [[ 1  1]
 [-1  1]]
Eigenvalues:
 [1.+1.j 1.-1.j]
Eigenvectors:
 [[0.70711+0.j      0.70711-0.j     ]
 [0.     +0.70711j 0.     -0.70711j]]


In [10]:
# symmetric matrix:
A=np.array([[1,2],[2,1]])
l,v=np.linalg.eig(A)
print('Matrix:\n',A)
print('Eigenvalues:\n',l)
print('Eigenvectors:\n',v.round(5))

Matrix:
 [[1 2]
 [2 1]]
Eigenvalues:
 [ 3. -1.]
Eigenvectors:
 [[ 0.70711 -0.70711]
 [ 0.70711  0.70711]]


In [11]:
print(v.T@v)

[[1. 0.]
 [0. 1.]]


In [12]:
# symmetric matrix with repeated eigenvalues:

A= np.array([[2,-1,-1], [-1,2,-1], [-1,-1,2]])
l, v=np.linalg.eig(A)

In [16]:
print('Matrix:\n',A)
print('Eigenvalues:\n',l.round(5))
print('Eigenvectors:\n',v.round(5))

Matrix:
 [[ 2 -1 -1]
 [-1  2 -1]
 [-1 -1  2]]
Eigenvalues:
 [ 3. -0.  3.]
Eigenvectors:
 [[ 0.8165  -0.57735  0.25359]
 [-0.40825 -0.57735 -0.79893]
 [-0.40825 -0.57735  0.54534]]


In [18]:
print(A@v[:,0], l[0]*v[:,0])
print(A@v[:,1], l[1]*v[:,1])
print(A@v[:,2], l[2]*v[:,2])

[ 2.44948974 -1.22474487 -1.22474487] [ 2.44948974 -1.22474487 -1.22474487]
[ 0.00000000e+00  2.22044605e-16 -3.33066907e-16] [2.44678814e-16 2.44678814e-16 2.44678814e-16]
[ 0.76078444 -2.39680122  1.63601679] [ 0.76078444 -2.39680122  1.63601679]
