In [1]:
import numpy as np

import plotly.graph_objects as go
from plotly.subplots import make_subplots

In [2]:
x=np.linspace(-5,5,100)
y=np.linspace(-5,5,100)

X,Y=np.meshgrid(x,y)
Z1=X**2+Y**2
Z2=X**2-Y**2
Z3=2*X*Y

# three figures side by side:

fig=make_subplots(rows=1,cols=3, specs=[[{'type':'surface'},{'type':'surface'},{'type':'surface'}]])
fig.add_trace(go.Surface(z=Z1,x=X,y=Y),row=1,col=1)
fig.add_trace(go.Surface(z=Z2,x=X,y=Y),row=1,col=2)
fig.add_trace(go.Surface(z=Z3,x=X,y=Y),row=1,col=3)
fig.update_layout(scene1_zaxis_range=[-25,25],scene2_zaxis_range=[-25,25],scene3_zaxis_range=[-25,25])
fig.update_traces(contours_z=dict(show=True,usecolormap=True,project_z=True))



fig.show()

In [3]:
A=np.array([[7, -4, 4], [-4, 5,0], [4, 0,9]])
print(A)

[[ 7 -4  4]
 [-4  5  0]
 [ 4  0  9]]


In [4]:
l, v=np.linalg.eig(A)
print(l)
print(v)

[ 1. 13.  7.]
[[ 0.66666667  0.66666667 -0.33333333]
 [ 0.66666667 -0.33333333  0.66666667]
 [-0.33333333  0.66666667  0.66666667]]
