In [1]:
import numpy as np

In [2]:
A=np.array([[.6, .8],[1.2,1.6], [1.2,1.6]])

In [3]:
U,s,Vt=np.linalg.svd(A)

In [4]:
with np.printoptions(precision=3): # Cleaning up the output a bit
    print("U=\n"+str(U)+"\n")
    print("s=\n"+str(s)+"\n")
    print("V=\n"+str(Vt.T))

U=
[[-3.333e-01  9.428e-01 -7.401e-17]
 [-6.667e-01 -2.357e-01 -7.071e-01]
 [-6.667e-01 -2.357e-01  7.071e-01]]

s=
[3.000e+00 1.884e-16]

V=
[[-0.6 -0.8]
 [-0.8  0.6]]


In [5]:
A.T@A

array([[3.24, 4.32],
       [4.32, 5.76]])