In [1]:
import numpy as np

In [2]:
A=np.array([[1.,1,0,0], [0,0,1,1], [1,1,1,1]])
print(A)

[[1. 1. 0. 0.]
 [0. 0. 1. 1.]
 [1. 1. 1. 1.]]


In [3]:
U, s, Vt = np.linalg.svd(A)

In [6]:
print(U)
print(s)
print(Vt)

[[ 4.08248290e-01  7.07106781e-01 -5.77350269e-01]
 [ 4.08248290e-01 -7.07106781e-01 -5.77350269e-01]
 [ 8.16496581e-01 -1.11022302e-16  5.77350269e-01]]
[2.44948974e+00 1.41421356e+00 1.44766737e-16]
[[ 5.00000000e-01  5.00000000e-01  5.00000000e-01  5.00000000e-01]
 [ 5.00000000e-01  5.00000000e-01 -5.00000000e-01 -5.00000000e-01]
 [-7.07106781e-01  7.07106781e-01 -1.57009246e-16 -1.57009246e-16]
 [ 7.13299383e-17 -7.13299383e-17 -7.07106781e-01  7.07106781e-01]]


Let us try computing using the eigenvalue algorithm instead. 

In [11]:
l, P = np.linalg.eig(A.T@A)
print(l)

[ 6.00000000e+00  2.00000000e+00 -2.84637279e-18  4.69370843e-16]


As we see, the algorithm returns negative eigenvalues. 

We know that the matrix $A^TA$ cannot have negative eigenvalues, but the basic eigenvaluealgorithm doesn't.

Additionally: The positive fourth eigenvalue returned above is small (it's around machine precision,) but its square is much larger.

In [13]:
print(l[3]**.5)

2.1664968110179272e-08


## Another example with stability problems

We create an example where we know the singular values to be $2, 1, 10^{-9}$. As we will see, `np.linalg.svd` computes the small singular value with a small error, but using `np.linalg.eig` on $A^TA$, we essentially

In [7]:
U=np.linalg.qr(np.random.rand(3,3))[0] # Random orthogonal matrix
V=np.linalg.qr(np.random.rand(3,3))[0]
S=np.diag([2,1,1e-9]) 
A=U@S@V.T
print(A)

[[ 0.01416284 -0.42451438  1.29149154]
 [ 1.12527105  0.49723915  1.23980015]
 [-0.11102658 -0.1723773   0.24291891]]


In [8]:
U,s,Vt=np.linalg.svd(A)
print(s)

[2.00000000e+00 1.00000000e+00 9.99999949e-10]


In [9]:
l,P=np.linalg.eig(A.T@A)
print(l)

[4.00000000e+00 1.00000000e+00 2.26946076e-16]


In [10]:
print(np.sqrt(l))

[2.00000000e+00 1.00000000e+00 1.50647295e-08]
