In [1]:
import numpy as np
import matplotlib.pyplot as plt

## Example 1
Small ill-conditioned matrix

In [2]:
A = np.array([[1., 1.], [1e-8,0], [0, 1e-8]])
b=np.array([1,0,0])

In [3]:
print("A=\n"+str(A))
print("b=\n"+str(b))

A=
[[1.e+00 1.e+00]
 [1.e-08 0.e+00]
 [0.e+00 1.e-08]]
b=
[1 0 0]


In [4]:
x=np.linalg.solve(A.T@A, A.T@b)

LinAlgError: Singular matrix

In [5]:
print(A.T@A)

[[1. 1.]
 [1. 1.]]


In [6]:
x=np.linalg.lstsq(A,b, rcond=None)[0]
print(x)

[0.5 0.5]


## Example 2:
A more "naturally occuring" example.
Regression polynomial with $x$-values:
$$ \{20,\ 20.25,\ 20.5,\ 20.75,\ 21\} $$

In [ ]:
x = np.linspace(20,21,5)
print("x=\n"+str(x))
print("\n")
deg=4
A=np.vander(x,deg+1, increasing=True)

ATA=A.T@A
with np.printoptions(precision=2, suppress=True): # Cleaning up the output a bit
    print("A=\n"+str(A))
    print("\n")
    print("A^TA=\n" + str(A.T@A))

In [ ]:
print("Condition number of ATA: "+str(np.linalg.cond(ATA)))

In [ ]:
y=1+x+x**2/2+x**3/6
betatrue=np.array([1.,1.,1/2,1/6, 0])

In [ ]:
betane=np.linalg.solve(ATA,A.T@y)
print(betane)
print("Relative error: " +str(np.linalg.norm(betane-betatrue)/np.linalg.norm(betatrue)))

In [ ]:
U,s,VT=np.linalg.svd(A, full_matrices=False)

print("Condition number=""{:e}".format(s[0]/s[-1]))

In [ ]:
betasvd=VT.T@((U.T@y)/s)
print(betasvd)
print("Relative error: " +str(np.linalg.norm(betasvd-betatrue)/np.linalg.norm(betatrue)))