In [1]:
import numpy as np

In [11]:
def Jacobi(A,b,k):
    n = b.shape[0]
    x = np.zeros(n)
    
    d=np.diagonal(A)
    N=np.diag(d)-A
    
    it=0
    for i in range(k): # Do this k times
        x=(b+N@x)/d
    return x

In [2]:
A=np.array([[ 6, -2,  3], 
            [-3,  9,  1], 
            [ 2, -1, -7]])
b=np.array([-1, 2, 3])
print(A)
print(b)

[[ 6 -2  3]
 [-3  9  1]
 [ 2 -1 -7]]
[-1  2  3]


In [4]:
d=np.diagonal(A)
print(d)

[ 6  9 -7]


In [6]:
np.diag(d)

array([[ 6,  0,  0],
       [ 0,  9,  0],
       [ 0,  0, -7]])

In [10]:
N=np.diag(d)-A
print(N)

[[ 0  2 -3]
 [ 3  0 -1]
 [-2  1  0]]


In [13]:
x=Jacobi(A,b,10)
print(x)
print(A@x-b)

[ 0.15567241  0.32190037 -0.43007845]
[-1.66849459e-06  7.69463554e-06 -6.39906572e-06]


In [20]:
def Jacobi_criterion(A,b):
    n = b.shape[0]
    x = np.zeros(n)
    
    
    tol = 1e-10
    maxit=100
    
    d=np.diagonal(A)
    N=A-np.diag(d)

    rem=np.linalg.norm(b-A@x)
    
    it=0
    while rem>tol and it<maxit:
        x=(b-N@x)/d
        rem=np.linalg.norm(b-A@x)
        it=it+1
    
    return x, it
       

(array([ 0.18611987,  0.33123028, -0.42271293]), 20)