In [1]:
import numpy as np

In [5]:
def power_method(A, x0, N, printing=False):
    x=x0
    for _ in range(N):
        y=A.dot(x)
        mu = y[np.argmax(np.abs(y))]
        x=y/mu
        if(printing):
            print("mu=")
            print(mu)
            print("x=")
            print(x)
            print("\n")
    return x, mu
        

In [6]:
#5.8.7
A=np.array([[6, 7], [8,5]])
x0=np.array([1,0])

In [10]:
x, mu = power_method(A,x0, 10)

In [8]:
#5.8.8
A=np.array([[2, 1], [4,5]])
x0=np.array([1,0])

In [9]:
x, mu=power_method(A, x0, 10, True)

mu=
4
x=
[0.5 1. ]


mu=
7.0
x=
[0.28571429 1.        ]


mu=
6.142857142857142
x=
[0.25581395 1.        ]


mu=
6.023255813953488
x=
[0.25096525 1.        ]


mu=
6.003861003861004
x=
[0.25016077 1.        ]


mu=
6.00064308681672
x=
[0.25002679 1.        ]


mu=
6.000107169649555
x=
[0.25000447 1.        ]


mu=
6.000017861289228
x=
[0.25000074 1.        ]


mu=
6.000002976872676
x=
[0.25000012 1.        ]


mu=
6.0000004961452
x=
[0.25000002 1.        ]




In [13]:
# Power Method doesn't always converge
A= np.array([[2, -3], [3, 2]])
x0=np.array([1,0])
power_method(A,x0, 10, True)

mu=
3
x=
[0.66666667 1.        ]


mu=
4.0
x=
[-0.41666667  1.        ]


mu=
-3.8333333333333335
x=
[ 1.         -0.19565217]


mu=
2.608695652173913
x=
[0.99166667 1.        ]


mu=
4.975
x=
[-0.20435511  1.        ]


mu=
-3.408710217755444
x=
[ 1.         -0.40687961]


mu=
3.22063882063882
x=
[1.         0.67882209]


mu=
4.35764418675618
x=
[-0.00836835  1.        ]


mu=
-3.016736694677871
x=
[ 1.         -0.65464612]


mu=
3.963938345829755
x=
[1.         0.42652222]


mu=
3.853044433057609
x=
[0.18697769 1.        ]


mu=
-2.6260446185190336
x=
[ 1.         -0.97520547]


mu=
4.925616405176347
x=
[1.         0.21308786]


mu=
3.4261757217280464
x=
[0.39715897 1.        ]


mu=
3.1914769071344837
x=
[-0.69111641  1.        ]


mu=
-4.382232819532289
x=
[1.         0.01673787]


mu=
3.0334757336358327
x=
[0.64275655 1.        ]


mu=
3.9282696524583325
x=
[-0.43644837  1.        ]


mu=
-3.8728967459187413
x=
[ 1.         -0.17833031]


mu=
2.6433393780251437
x=
[0.95901077 1.  

(array([0.80997919, 1.        ]), 2.8138781626670375)

In [22]:
def power_method_Rayleigh(A, x0, N, printing=False):
    x=x0
    for _ in range(N):
        y=A.dot(x)
        mu = y[np.argmax(np.abs(y))]
        r= x.dot(y)/x.dot(x)
        x=y/mu
        if(printing):
            print("mu= "+str(mu) + "\t r= "+str(r))
            print("x=")
            print(x)
            print("\n")
    return x, mu,r

In [23]:
# 5.8.11.
A=np.array([[5, 2], [2,2]])
x0=np.array([1,0])

In [24]:
power_method_Rayleigh(A,x0,10, True)

mu= 5	 r= 5.0
x=
[1.  0.4]


mu= 5.8	 r= 5.96551724137931
x=
[1.         0.48275862]


mu= 5.9655172413793105	 r= 5.999035679845709
x=
[1.         0.49710983]


mu= 5.994219653179191	 r= 5.999973208305425
x=
[1.         0.49951784]


mu= 5.999035679845709	 r= 5.9999992557823845
x=
[1.         0.49991963]


mu= 5.999839254139206	 r= 5.999999979327285
x=
[1.        0.4999866]


mu= 5.999973208305425	 r= 5.999999999425757
x=
[1.         0.49999777]


mu= 5.999995534697632	 r= 5.999999999984048
x=
[1.         0.49999963]


mu= 5.9999992557823845	 r= 5.999999999999557
x=
[1.         0.49999994]


mu= 5.999999875963716	 r= 5.9999999999999885
x=
[1.         0.49999999]




(array([1.        , 0.49999999]), 5.999999875963716, 5.9999999999999885)

In [27]:
def inv_power_method(A, x0, alpha, N, printing=False):
    x=x0
    I = np.eye(A.shape[-1])
    for _ in range(N):
        y=np.linalg.solve(A-alpha*I, x)
        mu = y[np.argmax(np.abs(y))]
        lam = alpha+1/mu
        x=y/mu
        if(printing):
            print("lambda= "+str(lam))
            print("x=")
            print(x)
            print("\n")
    return x, lam
        

In [33]:
# 5.8.17
A= np.array([[10, -8, -4],
             [-8, 13, 4],
             [-4, 5, 4]])
x0=np.array([1,0,0])
alpha=3.3
inv_power_method(A, x0, alpha, 5, True)

lambda= 3.3383800151400447
x=
[1.         0.78728236 0.09084027]


lambda= 3.321187545495297
x=
[1.         0.78698125 0.09574061]


lambda= 3.3212209417791327
x=
[1.         0.7870126  0.09566956]


lambda= 3.321220111648488
x=
[1.         0.78701212 0.09567073]


lambda= 3.321220124869812
x=
[1.         0.78701213 0.09567071]




(array([1.        , 0.78701213, 0.09567071]), 3.321220124869812)

In [32]:
np.linalg.eig(A)

(array([21.67877988,  3.32122012,  2.        ]),
 array([[-6.07945682e-01,  7.83611236e-01,  4.47213595e-01],
        [ 7.17296429e-01,  6.16711548e-01,  1.90445584e-16],
        [ 3.40423090e-01,  7.49686432e-02,  8.94427191e-01]]))

In [45]:
def jacobi(A, b, x0, Niter, printing=False):
    d=np.diag(A)
    N = A-np.diag(d)
    x=x0
    for _ in range(Niter):
        x=(b-N.dot(x))/d
        if(printing):
            print(x)
    return x

In [46]:
A= np.array([[5, 1, 2], 
             [-1,4,-1],
             [-2, 6, 10]])
b=np.array([1,1,1])
x0=np.zeros(3)

In [48]:
jacobi(A,b, x0,10, True)

[0.2  0.25 0.1 ]
[ 0.11   0.325 -0.01 ]
[ 0.139  0.275 -0.073]
[ 0.1742  0.2665 -0.0372]
[ 0.16158  0.28425 -0.02506]
[ 0.153174  0.28413  -0.038234]
[ 0.1584676  0.278735  -0.0398432]
[ 0.16019028  0.2796561  -0.03554748]
[ 0.15828777  0.2811607  -0.0357556 ]
[ 0.1580701   0.28063304 -0.03703887]


array([ 0.1580701 ,  0.28063304, -0.03703887])

In [40]:
A-np.diag(d)

array([[ 0,  1,  2],
       [-1,  0, -1],
       [-2,  6,  0]])