In [1]:
import numpy as np

5.9.26

In [2]:
P=np.array([[.9, .02, .08],[.02, .9, .02],[.08,.08,.9]])

In [3]:
P

array([[0.9 , 0.02, 0.08],
       [0.02, 0.9 , 0.02],
       [0.08, 0.08, 0.9 ]])

In [7]:
l, v =np.linalg.eig(P)
print(l)
print(v)

[1.   0.82 0.88]
[[-6.33750222e-01 -7.07106781e-01  7.07106781e-01]
 [-2.71607238e-01 -1.12331406e-15 -7.07106781e-01]
 [-7.24285968e-01  7.07106781e-01  1.21943009e-16]]


In [12]:
w=v[:,0]

In [13]:
w

array([-0.63375022, -0.27160724, -0.72428597])

In [14]:
q=w/sum(w)

In [15]:
q

array([0.38888889, 0.16666667, 0.44444444])