In [1]:
import numpy as np


A=np.array([[1.,1,0,0],
            [0,0,1,1],
            [1,1,1,1]])
print("A:\n", A)

U,s,VT=np.linalg.svd(A, full_matrices=True)
V=VT.T
print("U:\n", U)
print("s:\n", s)
print("V:\n", V)

A:
 [[1. 1. 0. 0.]
 [0. 0. 1. 1.]
 [1. 1. 1. 1.]]
U:
 [[ 4.08248290e-01  7.07106781e-01 -5.77350269e-01]
 [ 4.08248290e-01 -7.07106781e-01 -5.77350269e-01]
 [ 8.16496581e-01 -1.11022302e-16  5.77350269e-01]]
s:
 [2.44948974e+00 1.41421356e+00 1.44766737e-16]
V:
 [[ 5.00000000e-01  5.00000000e-01 -7.07106781e-01  7.13299383e-17]
 [ 5.00000000e-01  5.00000000e-01  7.07106781e-01 -7.13299383e-17]
 [ 5.00000000e-01 -5.00000000e-01 -1.57009246e-16 -7.07106781e-01]
 [ 5.00000000e-01 -5.00000000e-01 -1.57009246e-16  7.07106781e-01]]


In [2]:
Sigma=np.zeros_like(A)
Sigma[:len(s), :len(s)] = np.diag(s)
print("Sigma:\n", Sigma)

Sigma:
 [[2.44948974e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 1.41421356e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 1.44766737e-16 0.00000000e+00]]


In [3]:
U,s,VT=np.linalg.svd(A, full_matrices=False)
V=VT.T
print("U:\n", U)
print("s:\n", s)
print("V:\n", V)

U:
 [[ 4.08248290e-01  7.07106781e-01 -5.77350269e-01]
 [ 4.08248290e-01 -7.07106781e-01 -5.77350269e-01]
 [ 8.16496581e-01 -1.11022302e-16  5.77350269e-01]]
s:
 [2.44948974e+00 1.41421356e+00 1.44766737e-16]
V:
 [[ 5.00000000e-01  5.00000000e-01 -7.07106781e-01]
 [ 5.00000000e-01  5.00000000e-01  7.07106781e-01]
 [ 5.00000000e-01 -5.00000000e-01 -1.57009246e-16]
 [ 5.00000000e-01 -5.00000000e-01 -1.57009246e-16]]
